
DROP DATABASE IF EXISTS `mapping-scientific`;
CREATE DATABASE IF NOT EXISTS `mapping-scientific` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `mapping-scientific`;

CREATE TABLE `document` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`source_id` INT(11) NULL DEFAULT NULL,
	`type` VARCHAR(255) NULL DEFAULT NULL,
	`title_slug` VARCHAR(255) NULL DEFAULT NULL,
	`title` VARCHAR(255) NULL DEFAULT NULL,
	`abstract` TEXT NULL,
	`authors` TEXT NULL,
	`year` VARCHAR(255) NULL DEFAULT NULL,
	`volume` VARCHAR(255) NULL DEFAULT NULL,
	`issue` VARCHAR(255) NULL DEFAULT NULL,
	`issn` VARCHAR(255) NULL DEFAULT NULL,
	`isbns` VARCHAR(255) NULL DEFAULT NULL,
	`doi` VARCHAR(255) NULL DEFAULT NULL,
	`pdf_link` VARCHAR(255) NULL DEFAULT NULL,
	`pdf_path_local` VARCHAR(255) NULL DEFAULT NULL,
	`keywords` TEXT NULL,
	`published_in` VARCHAR(255) NULL DEFAULT NULL,
	`numpages` VARCHAR(255) NULL DEFAULT NULL,
	`pages` VARCHAR(255) NULL DEFAULT NULL,
	`publisher` VARCHAR(255) NULL DEFAULT NULL,
	`source` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Bases',
	`search_string` VARCHAR(255) NULL DEFAULT NULL,
	`duplicate` SMALLINT(6) NULL DEFAULT '0',
	`duplicate_id` INT(11) NULL DEFAULT NULL,
	`cited` INT(11) NULL DEFAULT NULL,
	`full_text` TEXT NULL,
	PRIMARY KEY (`id`),
	INDEX `title` (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

